enum AuditEntityType {
  companies('companies'),
  companyParameters('company_parameters'),
  locations('locations'),
  areas('areas'),
  categories('categories'),
  assets('assets'),
  checklistTemplates('checklist_templates'),
  checklistItems('checklist_items'),
  maintenancePlans('maintenance_plans'),
  workOrders('work_orders'),
  tasks('tasks'),
  workOrderChangeRequests('work_order_change_requests'),
  workOrderObservations('work_order_observations'),
  attachments('attachments'),
  workOrderPauseRequests('work_order_pause_requests'),
  userProfiles('user_profiles'),
  permissionGroups('permission_groups'),
  slaPolicies('sla_policies'),
  sectors('sectors'),
  pauseReasons('pause_reasons'),
  serviceProviderCompanies('service_provider_companies'),
  serviceProviderProfiles('service_provider_profiles'),
  unknown('');

  const AuditEntityType(this.code);
  final String code;

  static AuditEntityType fromCode(String? code) => switch (code) {
    'companies' => AuditEntityType.companies,
    'company_parameters' => AuditEntityType.companyParameters,
    'locations' => AuditEntityType.locations,
    'areas' => AuditEntityType.areas,
    'categories' => AuditEntityType.categories,
    'assets' => AuditEntityType.assets,
    'checklist_templates' => AuditEntityType.checklistTemplates,
    'checklist_items' => AuditEntityType.checklistItems,
    'maintenance_plans' => AuditEntityType.maintenancePlans,
    'work_orders' => AuditEntityType.workOrders,
    'tasks' => AuditEntityType.tasks,
    'work_order_change_requests' => AuditEntityType.workOrderChangeRequests,
    'work_order_observations' => AuditEntityType.workOrderObservations,
    'attachments' => AuditEntityType.attachments,
    'work_order_pause_requests' => AuditEntityType.workOrderPauseRequests,
    'user_profiles' => AuditEntityType.userProfiles,
    'permission_groups' => AuditEntityType.permissionGroups,
    'sla_policies' => AuditEntityType.slaPolicies,
    'sectors' => AuditEntityType.sectors,
    'pause_reasons' => AuditEntityType.pauseReasons,
    'service_provider_companies' => AuditEntityType.serviceProviderCompanies,
    'service_provider_profiles' => AuditEntityType.serviceProviderProfiles,
    _ => AuditEntityType.unknown,
  };
}
