import 'package:clean_architecture/features/work_orders/domain/entities/priority.dart';
import 'package:clean_architecture/features/work_orders/domain/entities/work_order_status.dart';
import 'package:clean_architecture/features/work_orders/domain/entities/work_order_type.dart';
import 'package:equatable/equatable.dart';

class WorkOrderEntity extends Equatable {
  const WorkOrderEntity({
    required this.id,
    required this.companyId,
    this.assetId,
    required this.locationId,
    this.assignedToId,
    required this.createdById,
    this.maintenancePlanId,
    required this.title,
    this.description,
    required this.priority,
    required this.status,
    required this.type,
    this.scheduledDate,
    this.startedAt,
    this.completedAt,
    this.estimatedDuration,
    this.actualDuration,
    this.laborCost,
    this.partsCost,
    this.totalCost,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final String id;
  final String companyId;
  final String? assetId;
  final String locationId;
  final String? assignedToId;
  final String createdById;
  final String? maintenancePlanId;
  final String title;
  final String? description;
  final Priority priority;
  final WorkOrderStatus status;
  final WorkOrderType type;
  final DateTime? scheduledDate;
  final DateTime? startedAt;
  final DateTime? completedAt;
  final int? estimatedDuration;
  final int? actualDuration;
  final double? laborCost;
  final double? partsCost;
  final double? totalCost;
  final String? notes;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;

  @override
  List<Object?> get props => [
        id,
        companyId,
        assetId,
        locationId,
        assignedToId,
        createdById,
        maintenancePlanId,
        title,
        description,
        priority,
        status,
        type,
        scheduledDate,
        startedAt,
        completedAt,
        estimatedDuration,
        actualDuration,
        laborCost,
        partsCost,
        totalCost,
        notes,
        createdAt,
        updatedAt,
        deletedAt,
      ];

  WorkOrderEntity copyWith({
    String? id,
    String? companyId,
    String? assetId,
    String? locationId,
    String? assignedToId,
    String? createdById,
    String? maintenancePlanId,
    String? title,
    String? description,
    Priority? priority,
    WorkOrderStatus? status,
    WorkOrderType? type,
    DateTime? scheduledDate,
    DateTime? startedAt,
    DateTime? completedAt,
    int? estimatedDuration,
    int? actualDuration,
    double? laborCost,
    double? partsCost,
    double? totalCost,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? deletedAt,
  }) {
    return WorkOrderEntity(
      id: id ?? this.id,
      companyId: companyId ?? this.companyId,
      assetId: assetId ?? this.assetId,
      locationId: locationId ?? this.locationId,
      assignedToId: assignedToId ?? this.assignedToId,
      createdById: createdById ?? this.createdById,
      maintenancePlanId: maintenancePlanId ?? this.maintenancePlanId,
      title: title ?? this.title,
      description: description ?? this.description,
      priority: priority ?? this.priority,
      status: status ?? this.status,
      type: type ?? this.type,
      scheduledDate: scheduledDate ?? this.scheduledDate,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      estimatedDuration: estimatedDuration ?? this.estimatedDuration,
      actualDuration: actualDuration ?? this.actualDuration,
      laborCost: laborCost ?? this.laborCost,
      partsCost: partsCost ?? this.partsCost,
      totalCost: totalCost ?? this.totalCost,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      deletedAt: deletedAt ?? this.deletedAt,
    );
  }

  WorkOrderEntity annulAssetId() => copyWith(assetId: null); // copyWith sets it to this.assetId if null, so we must write a manual helper to set it to null
  WorkOrderEntity annulAssignedToId() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: null,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulMaintenancePlanId() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: null,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulScheduledDate() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: null,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulStartedAt() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: null,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulCompletedAt() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: null,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulEstimatedDuration() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: null,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulActualDuration() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: null,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulLaborCost() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: null,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulPartsCost() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: null,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulTotalCost() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: null,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulNotes() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: null,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: deletedAt,
      );
  WorkOrderEntity annulDeletedAt() => WorkOrderEntity(
        id: id,
        companyId: companyId,
        assetId: assetId,
        locationId: locationId,
        assignedToId: assignedToId,
        createdById: createdById,
        maintenancePlanId: maintenancePlanId,
        title: title,
        description: description,
        priority: priority,
        status: status,
        type: type,
        scheduledDate: scheduledDate,
        startedAt: startedAt,
        completedAt: completedAt,
        estimatedDuration: estimatedDuration,
        actualDuration: actualDuration,
        laborCost: laborCost,
        partsCost: partsCost,
        totalCost: totalCost,
        notes: notes,
        createdAt: createdAt,
        updatedAt: updatedAt,
        deletedAt: null,
      );
}
