// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfG3IQJc_K-ggfUbYnOrYlC-HBBd-R-4',
    appId: '1:738276498188:web:2c6d8a095a5da838f8c729',
    messagingSenderId: '738276498188',
    projectId: 'serviceproviders-733e7',
    authDomain: 'serviceproviders-733e7.firebaseapp.com',
    storageBucket: 'serviceproviders-733e7.firebasestorage.app',
    measurementId: 'G-LPHDNNE2G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTDQsuTXGyAqfOeVGTexPSUgvrjue6ivQ',
    appId: '1:738276498188:android:4a1b91d8788490edf8c729',
    messagingSenderId: '738276498188',
    projectId: 'serviceproviders-733e7',
    storageBucket: 'serviceproviders-733e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBZMIW39vxd6n5x_tTjryfCxgzSCG8kzw',
    appId: '1:738276498188:ios:5e1d7fcd8a623504f8c729',
    messagingSenderId: '738276498188',
    projectId: 'serviceproviders-733e7',
    storageBucket: 'serviceproviders-733e7.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfG3IQJc_K-ggfUbYnOrYlC-HBBd-R-4',
    appId: '1:738276498188:web:d8b8465b7b390b05f8c729',
    messagingSenderId: '738276498188',
    projectId: 'serviceproviders-733e7',
    authDomain: 'serviceproviders-733e7.firebaseapp.com',
    storageBucket: 'serviceproviders-733e7.firebasestorage.app',
    measurementId: 'G-NR5RLCEFQW',
  );
}
