// Aggregates the per-suite JSONL written by `checkedTest` into the single
// human-readable catalogue at INTEGRATION_TEST_ERRORS.md.
//
// Run automatically by tool/run_integration_tests.sh; safe to run by hand.
import 'dart:convert';
import 'dart:io';

import 'integration_run_summary.dart';

String _reportDir =
    Platform.environment['INTEGRATION_REPORT_DIR'] ??
    'build/integration_report';

void main() {
  final directory = Directory(_reportDir);
  final runner = File('$_reportDir/runner.jsonl');
  if (!directory.existsSync() || !runner.existsSync()) {
    stderr.writeln(
      'Missing runner evidence; refusing an empty passing report.',
    );
    exitCode = 1;
    return;
  }
  final summary = IntegrationRunSummary.parse(runner.readAsStringSync());
  final catalogue = <Map<String, Object?>>[];
  for (final file in directory.listSync().whereType<File>()) {
    if (!file.path.endsWith('.jsonl') || file.path == runner.path) continue;
    for (final line in file.readAsLinesSync()) {
      if (line.trim().isEmpty) continue;
      try {
        final record = jsonDecode(line) as Map<String, Object?>;
        if (record['id'] != null && record['outcome'] != null) {
          catalogue.add(record);
        }
      } on Object {
        summary.problems.add('Malformed catalogue evidence');
      }
    }
  }
  for (final record in catalogue) {
    final matches = summary.records
        .where(
          (r) => (r['description']! as String).startsWith('${record['id']} —'),
        )
        .toList();
    if (matches.length != 1) {
      summary.problems.add(
        'Catalogue case missing/duplicated in runner: ${record['id']}',
      );
      continue;
    }
    final target = matches.single;
    final runnerOutcome = target['outcome'];
    target.addAll(record);
    if (runnerOutcome != 'passed') target['outcome'] = runnerOutcome;
  }
  for (final file in directory.listSync().whereType<File>()) {
    if (!file.path.split('/').last.startsWith('cleanup-')) continue;
    final cleanup = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    if ((cleanup['errors'] as List?)?.isNotEmpty ?? false) {
      summary.problems.add(
        'Fixture cleanup remains unresolved; see cleanup ledger',
      );
    }
  }
  final output = File('$_reportDir/report.md')
    ..writeAsStringSync(
      '${_render(summary.records)}\n'
      '## Run integrity\n\n'
      '${summary.problems.isEmpty ? 'Complete runner evidence.' : summary.problems.map((p) => '- $p').join('\n')}\n',
    );
  stdout.writeln(
    'Report: ${output.path}; ${summary.records.length} cases; '
    '${summary.passed ? 'PASSED' : 'FAILED OR BLOCKED'}',
  );
  if (!summary.passed) exitCode = 1;
}

String _render(List<Map<String, Object?>> records) {
  final buffer = StringBuffer()
    ..writeln('# Integration test findings — ServicePro')
    ..writeln()
    ..writeln(
      'Generated by `tool/build_integration_report.dart` on '
      '${DateTime.now().toIso8601String()}.',
    )
    ..writeln()
    ..writeln(
      'Executed against the **live** Supabase project. This pass catalogues '
      'failures; it does not fix them.',
    )
    ..writeln();

  _writeSummary(buffer, records);
  _writeManualCleanup(buffer);
  _writeFailures(buffer, records);
  _writeSkipped(buffer, records);
  _writeNotes(buffer, records);
  return buffer.toString();
}

void _writeSummary(StringBuffer buffer, List<Map<String, Object?>> records) {
  final byFeature = <String, Map<String, int>>{};
  for (final record in records) {
    final feature = record['feature'] as String? ?? 'unknown';
    final outcome = record['outcome'] as String? ?? 'unknown';
    final counts = byFeature.putIfAbsent(
      feature,
      () => {'passed': 0, 'failed': 0, 'skipped': 0},
    );
    counts[outcome] = (counts[outcome] ?? 0) + 1;
  }

  buffer
    ..writeln('## Summary')
    ..writeln()
    ..writeln('| Feature area | Passed | Failed | Skipped | Total |')
    ..writeln('|---|---:|---:|---:|---:|');

  var passed = 0;
  var failed = 0;
  var skipped = 0;
  for (final feature in byFeature.keys.toList()..sort()) {
    final counts = byFeature[feature]!;
    final total = counts.values.reduce((a, b) => a + b);
    passed += counts['passed']!;
    failed += counts['failed']!;
    skipped += counts['skipped']!;
    buffer.writeln(
      '| $feature | ${counts['passed']} | ${counts['failed']} '
      '| ${counts['skipped']} | $total |',
    );
  }
  buffer
    ..writeln(
      '| **Total** | **$passed** | **$failed** | **$skipped** '
      '| **${records.length}** |',
    )
    ..writeln();
}

void _writeFailures(StringBuffer buffer, List<Map<String, Object?>> records) {
  final failures = records.where((r) => r['outcome'] == 'failed').toList();
  buffer
    ..writeln('## Failures')
    ..writeln();
  if (failures.isEmpty) {
    buffer
      ..writeln('_No failing cases in this run._')
      ..writeln();
    return;
  }
  for (final record in failures) {
    _writeCase(buffer, record);
  }
}

void _writeCase(StringBuffer buffer, Map<String, Object?> record) {
  final error = record['error'] as Map<String, Object?>?;
  buffer
    ..writeln('### ${record['id']} — ${record['description']}')
    ..writeln(
      '- Feature: ${record['feature']}  |  Role: ${record['role'] ?? '—'}  '
      '|  Layer: ${record['layer']}',
    );

  final steps = (record['steps'] as List?)?.cast<String>() ?? const [];
  if (steps.isNotEmpty) {
    buffer.writeln('- Steps: ${steps.join(' -> ')}');
  }
  if (record['expected'] != null) {
    buffer.writeln('- Expected: ${record['expected']}');
  }
  if (record['actual'] != null) {
    buffer.writeln('- Actual:   ${_oneLine(record['actual']! as String)}');
  }
  if (error != null) {
    buffer.writeln(
      '- Error:    ${error['type']}'
      '${error['code'] != null ? ' (code ${error['code']})' : ''}'
      '${error['message'] != null ? ' — ${_oneLine(error['message']! as String)}' : ''}',
    );
    if (error['hint'] != null) buffer.writeln('- Hint:     ${error['hint']}');
  }
  final notes = (record['notes'] as List?)?.cast<String>() ?? const [];
  for (final note in notes) {
    buffer.writeln('- Note:     $note');
  }
  if (record['stack'] != null) {
    final stack = (record['stack']! as String).split('\n').take(6).join('\n');
    buffer
      ..writeln()
      ..writeln('```')
      ..writeln(stack)
      ..writeln('```');
  }
  buffer.writeln();
}

void _writeSkipped(StringBuffer buffer, List<Map<String, Object?>> records) {
  final skipped = records.where((r) => r['outcome'] == 'skipped').toList();
  if (skipped.isEmpty) return;
  buffer
    ..writeln('## Not executable')
    ..writeln()
    ..writeln(
      'Cases whose preconditions could not be provisioned. These are '
      'explicitly **not** passes.',
    )
    ..writeln()
    ..writeln('| Case | Feature | Reason |')
    ..writeln('|---|---|---|');
  for (final record in skipped) {
    buffer.writeln(
      '| ${record['id']} | ${record['feature']} '
      '| ${_oneLine((record['skipReason'] as String?) ?? '—')} |',
    );
  }
  buffer.writeln();
}

void _writeNotes(StringBuffer buffer, List<Map<String, Object?>> records) {
  final noted = records
      .where(
        (r) =>
            r['outcome'] != 'failed' &&
            ((r['notes'] as List?)?.isNotEmpty ?? false),
      )
      .toList();
  if (noted.isEmpty) return;
  buffer
    ..writeln('## Findings from passing cases')
    ..writeln()
    ..writeln(
      'Behaviour that did not fail an assertion but is recorded as a '
      'finding — typically a permissive RLS policy the catalogue predicted.',
    )
    ..writeln();
  for (final record in noted) {
    buffer.writeln('- **${record['id']}** (${record['feature']})');
    for (final note in (record['notes']! as List).cast<String>()) {
      buffer.writeln('  - $note');
    }
  }
  buffer.writeln();
}

void _writeManualCleanup(StringBuffer buffer) {
  buffer
    ..writeln('## Fixture cleanup')
    ..writeln()
    ..writeln(
      'See the run cleanup JSON and durable `.integration-test-state/` '
      'ledgers for exact IDs and unresolved operations. Append-only records '
      'are retained according to the deployed schema. No prefix sweep is authorized.',
    )
    ..writeln();
}

String _oneLine(String value) =>
    value.replaceAll('\n', ' ').replaceAll('|', r'\|').trim();
